[project]
name = 'droplinked-stacks-contract'
description = 'droplinked is a commerce infrastructure network operating as a decentralized inventory management and sales tracking system for digital and physical goods.'
authors = ['yeganegierfan@gmail.com']
telemetry = true
cache_dir = './.cache'

[contracts.sft-trait]
path = 'contracts/sft-trait.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = true, trusted_caller = true, callee_filter = true }

[devnet]
use_nakamoto = true
